### ISSUE TITLE
BUG: Duplication of certain rows in `geolife_add_modes_to_triplegs`

### ISSUE THREAD

**Issue by bifbof** [mie-lab/trackintel#273]
Running `geolife_add_modes_to_triplegs` returns a dataframe with more rows out than in (duplicates).
The `tpls_id_mode` already has an index with duplicates, so it is just passed on when joined to the `tpls` on line 257. https://github.com/mie-lab/trackintel/blob/dc9c6efe28ec0b736ee8da5a243cb86b8b83eeb2/trackintel/io/dataset_reader.py#L257

Tested with user 52 from the geolife dataset.
````python
import trackintel as ti
from trackintel.io.dataset_reader import read_geolife, geolife_add_modes_to_triplegs

pfs, mode_labels = read_geolife(r".\geolife_user52", print_progress=True)

# generate triplegs
pfs, spts = pfs.as_positionfixes.generate_staypoints(time_threshold=5.0, print_progress=True)
pfs, tpls_pre = pfs.as_positionfixes.generate_triplegs(spts)
tpls_post = geolife_add_modes_to_triplegs(tpls_pre, mode_labels)

assert len(tpls_pre) == len(tpls_post)

````

**Comment by hong2223** [comment]
I am not sure if I understand the problem. The sample code runs without error in my environment (tpls_pre has the same number of records as tpls_post). 

Could you elaborate on the issue more? Is it because tpls_id_mode could contain duplicated index?

**Comment by bifbof** [comment]
It was solved by PR #238, I'll close this one. :)

**Comment by henrymartin1** [comment]
The issue still persists, I just tested it for geolife user 20
